//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "item_stack")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub expires_at: Option<DateTime>,
    pub cash_id: Option<i64>,
    pub item_id: i32,
    pub flags: i32,
    pub quantity: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::inventory_slot::Entity")]
    InventorySlot,
}

impl Related<super::inventory_slot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventorySlot.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
